### ISSUE TITLE
Cannot download tracked memory leaks

### ISSUE THREAD

**Issue by Thioby** [dart-lang/leak_tracker#105] opened 2023-07-27 08:12 UTC
On version 8.0.3 you are not able to download tracked memory leaks.
<img width="670" alt="Screenshot 2023-07-27 at 10 06 05" src="https://github.com/dart-lang/leak_tracker/assets/8046733/7c29ce13-7acc-494e-aa9b-0525001bdd18">

The problem is here: (`_protocol.dart`)

<img width="891" alt="Screenshot 2023-07-27 at 10 06 37" src="https://github.com/dart-lang/leak_tracker/assets/8046733/57fd5dcf-867b-46f3-a26c-2cb786d00941">

As you can see there is 7 types of envelopes, but type that is looked for is `Future<Leaks>` . Envelope is not found, null from map and  then is forced to be not a null, that's why is crashing.

Class `class ResponseFromApp<T extends Object> ` allows passing any object as message. So in case of leaks, as a message is passed Future<Leaks> instead of Leaks itself.

Solution:

In file `_registration.dart` at line 50 add `await` before creating `ResponseFromApp` object
```

      if (request is RequestForLeakDetails) {
        return ResponseFromApp(await theLeakProvider.collectLeaks())
            .toServiceResponse();
      }
```

**Comment by polina-c** [comment] 2023-08-06 16:56
Thank you for reporting. This should be addressed.

**Comment by polina-c** [comment] 2023-08-14 21:32
Subtask of https://github.com/flutter/devtools/issues/3951

**Comment by polina-c** [comment] 2023-11-02 19:15
Closing as duplicate of https://github.com/dart-lang/leak_tracker/issues/172

**Closed by polina-c** 2023-11-02 19:15 UTC
Labels: subtask
